[formatter.typos]
command = "typos"
options = ["--write-changes", "--force-exclude"]
includes = ["*"]
excludes = [
  ".gitignore",
  "*.kicad_*",
]

[formatter.nix]
command = "alejandra"
includes = [ "*.nix" ]

[formatter.shell]
command = "shellcheck"
includes = [ "*.sh" ]
