esphome:
  name: boiler

esp32:
  board: esp32dev
  framework:
    type: arduino

packages:
  base: !include ../../esphome_common/base.yaml
  ethernet: !include ../../esphome_common/ethernet_ttgo_tinternet_poe.yaml

# spares 16, 32

dallas:
  - pin: GPIO14

switch:
  - name: Boiler Heating Demand
    platform: gpio
    pin:
      number: GPIO2

binary_sensor:
  - name: Boiler Hot Water Demand
    platform: gpio
    pin:
      number: GPIO16
      mode:
        input: true
      inverted: true

  - name: Boiler Heating Demand
    platform: gpio
    pin:
      number: GPIO36
      mode:
        input: true
      inverted: true

  - name: Boiler Flame Lit
    platform: gpio
    pin:
      number: GPIO34
      mode:
        input: true
      inverted: true

sensor:
#   - name: Boiler Smart Interface Electronics Temperature
#     platform: dallas
#     address: 0xd63ce1e380a63428
#
  - name: Boiler Closet Temperature
    platform: dallas
    address: 0x9e3ce1e3803b3a28

  - name: "Cold Water Inlet Temperature"
    platform: dallas
    address: 0x023c490457f76428

  - name: "Hot Water Flow Temperature"
    platform: dallas
    address: 0xeb000f9843140528

  - name: "Central Heating Flow Temperature"
    platform: dallas
    address: 0x4b00ff9843122b28

  - name: "Central Heating Return Temperature"
    platform: dallas
    address: 0xfa00239843066d28
