---
status_led:
  pin: GPIO2

i2c:
  sda: GPIO32
  scl: GPIO33

uart:
  - id: uart_1
    rx_pin: GPIO19
    tx_pin: GPIO21
    baud_rate: 9600

  - id: uart_2
    rx_pin: GPIO17
    tx_pin: GPIO18
    baud_rate: 9600

sx1509:
  - id: sx1509_hub1
    address: 0x3E

dallas:
  - pin: GPIO23
