---
i2c:
  sda: GPIO33
  scl: GPIO4

uart:
  - id: uart_1
    rx_pin: GPIO34
    tx_pin: GPIO16
    baud_rate: 9600

  - id: uart_2
    rx_pin: GPIO35
    tx_pin: GPIO32
    baud_rate: 9600

dallas:
  - pin: GPIO14
