---
esphome:
  name: board-2

esp32:
  board: esp32dev
  framework:
    type: arduino

packages:
  base: !include ../esphome_common/base.yaml
  ethernet: !include ../esphome_common/ethernet_ttgo_tinternet_poe.yaml

binary_sensor:
  - platform: gpio
    pin:
      number: 16
      mode:
        input: true
        pullup: true
    name: Front Door
    device_class: door

  - platform: gpio
    pin:
      number: 33
      mode:
        input: true
        pullup: true
    name: Front Door Tamper
    device_class: tamper
