---
esphome:
  name: utility-room

esp8266:
  board: d1_mini

packages:
  base: !include ../common/base.yaml
  wifi: !include ../common/wifi.yaml

i2c:

binary_sensor:
  - platform: gpio
    pin:
      number: D6
      mode:
        input: true
        pullup: true
    name: Back Door - Left
    device_class: door

  - platform: gpio
    pin:
      number: D7
      mode:
        input: true
        pullup: true
    name: Back Door - Right
    device_class: door

  - platform: gpio
    pin:
      number: D5
      mode:
        input: true
        pullup: true
    name: Utility Room Door
    device_class: door

  - platform: gpio
    pin:
      number: RX
      mode:
        input: true
        pullup: true
    name: Utility Room Doors Tamper
    device_class: tamper

  - platform: gpio
    pin: D0
    name: Utility Room Motion
    device_class: motion
    filters:
      - delayed_off: 15s

sensor:
  - platform: wifi_signal
    name: Utility Room WiFi Signal Strength
    update_interval: 60s

  - platform: adc
    pin: A0
    name: Utility Room Ambient Brightness
    device_class: illuminance
    unit_of_measurement: "%"
    update_interval: 1s
    accuracy_decimals: 0
    filters:
      - multiply: 100
      - delta: 2%

  - platform: aht10
    temperature:
      name: Utility Room Temperature
      id: temperature
      accuracy_decimals: 1
      filters:
        - offset: -4.0
    humidity:
      name: Utility Room Humidity
      id: relative_humidity
      accuracy_decimals: 1
    update_interval: 60s

  - platform: absolute_humidity
    name: Utility Room Absolute Humidity
    temperature: temperature
    humidity: relative_humidity
