---
esphome:
  name: hakkero
  build_path: build
  platform: ESP8266
  board: nodemcuv2

packages:
  base: !include ../../common/base.yaml
  wifi: !include ../../common/wifi.yaml

wifi:
  ap:
    ssid: "fix_me_hakkero"

light:
  - platform: fastled_clockless
    name: "Hakkero"
    chipset: WS2811
    pin: D7
    num_leds: 59
    rgb_order: GRB
    effects:
      - random:
      - flicker:
