esphome:
  name: doit-esp32-devkit-kitchen-sink

esp32:
  board: esp32dev
  framework:
    type: arduino

packages:
  base: !include ../../esphome_common/base.yaml
  wifi: !include ../../esphome_common/wifi.yaml
  breakout: !include ../../esphome_common/doit-esp32-devkit-breakout.yaml

web_server:
  port: 80

sensor:
  - platform: sgp4x
    voc:
      name: "VOC Index"
    nox:
      name: "NOx Index"

  - platform: bh1750
    name: "Ambient Light"
    update_interval: 5s

  - platform: pmsx003
    uart_id: uart_1
    update_interval: 60s
    type: PMSX003
    pm_1_0:
      name: "Particulate Matter <1.0µm"
    pm_2_5:
      name: "Particulate Matter <2.5µm"
    pm_10_0:
      name: "Particulate Matter <10.0µm"

  - platform: senseair
    uart_id: uart_2
    co2:
      name: "CO2"

  - platform: dallas
    address: 0xbf83d55709646128
    name: "Dallas Temperature"

  - platform: aht10
    temperature:
      name: "Temperature"
    humidity:
      name: "Humidity"

light:
  - platform: neopixelbus
    type: BRG
    variant: WS2812
    pin: GPIO14
    num_leds: 24
    name: "NeoPixel Light"

binary_sensor:
  - platform: gpio
    name: "SX1509 Pin #0"
    pin:
      sx1509: sx1509_hub1
      number: 0
      mode:
        input: true
        pullup: true
      inverted: true
