---
name: Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        device:
          - board-1.yaml
          - board-2.yaml
          - board-3.yaml
          - boiler.yaml
          - guest-bedroom.yaml
          - kitchen.yaml
          - landing.yaml
          - living-room.yaml
          - main-bedroom.yaml
          - office.yaml
          - utility-room.yaml
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Install ESPHome
        run: pip install esphome

      - name: Build
        run: |
          ./secrets.sh dummy devices/${{ matrix.device }}
          esphome compile devices/${{ matrix.device }}
