---
name: Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        device:
          - boiler/boiler.yaml
          - flan-wings/flan-wings.yaml
          - hakkero/hakkero.yaml
          - room-sensor/room-sensor.yaml
          - vfd-clock/vfd-clock.yaml
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Install ESPHome
        run: pip install esphome

      - name: Copy dummy secrets file
        run: cp common/secrets_empty.yaml common/secrets.yaml

      - name: Build
        run: esphome compile devices/${{ matrix.device }}
