---
name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        device:
          - board-2.yaml
          - board-3.yaml
          - board-4.yaml
          - boiler/boiler.yaml
          - guest-bedroom.yaml
          - kitchen.yaml
          - landing.yaml
          - living-room.yaml
          - main-bedroom.yaml
          - office.yaml
          - utility-room.yaml

    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v22

      - name: Build
        run: |
          ./secrets.sh dummy devices/${{ matrix.device }}
          nix develop --command esphome compile devices/${{ matrix.device }}
