---
name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v16
        with:
          name: devenv
      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv

      - name: Formatting and Linting
        shell: devenv shell bash -- -e {0}
        run: treefmt --verbose --fail-on-change

  build:
    runs-on: ubuntu-latest
    needs:
      - quality

    strategy:
      matrix:
        device:
          - board-2/board-2.yaml
          - board-3/board-3.yaml
          - board-4/board-4.yaml
          - boiler/boiler.yaml
          - doit-esp32-devkit-kitchen-sink/doit-esp32-devkit-kitchen-sink.yaml
          # - flan-wings/flan-wings.yaml
          # - hakkero/hakkero.yaml
          - utility-room/utility-room.yaml
          # - vfd-clock/vfd-clock.yaml

    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v16
        with:
          name: devenv
      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv

      - name: Build
        shell: devenv shell bash -- -e {0}
        run: |
          ./secrets.sh dummy devices/${{ matrix.device }}
          esphome compile devices/${{ matrix.device }}
