---
name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v26

      - name: Formatting and Linting
        run: nix develop --command treefmt --verbose --fail-on-change

  build:
    runs-on: ubuntu-latest

    needs:
      - quality

    strategy:
      matrix:
        device:
          - board-2/board-2.yaml
          - board-3/board-3.yaml
          - board-4/board-4.yaml
          - boiler/boiler.yaml
          - doit-esp32-devkit-kitchen-sink/doit-esp32-devkit-kitchen-sink.yaml
          # - flan-wings/flan-wings.yaml
          - guest-bedroom/guest-bedroom.yaml
          # - hakkero/hakkero.yaml
          - kitchen/kitchen.yaml
          - landing/landing.yaml
          - living-room/living-room.yaml
          - main-bedroom/main-bedroom.yaml
          - office/office.yaml
          - utility-room/utility-room.yaml
          # - vfd-clock/vfd-clock.yaml

    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v26

      - name: Build
        run: |
          ./secrets.sh dummy devices/${{ matrix.device }}
          nix develop --command esphome compile devices/${{ matrix.device }}
